name: Feature Request
description: Suggest a new feature or enhancement for the STL Previewer extension
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature you'd like to see implemented...
    validations:
      required: true

  - type: textarea
    id: problem-use-case
    attributes:
      label: Problem/Use Case
      description: Describe the problem this feature would solve, or the use case it would enable
      placeholder: Explain what problem this feature would solve or what use case it would enable...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: Describe your vision for how this feature should work...
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: Have you considered other approaches? Describe them here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
      placeholder: Any additional information, mockups, or examples that might be helpful...
      render: markdown

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: I have checked the [FAQ](../../docs/FAQ.md)
          required: true
        - label: This feature would benefit multiple users, not just my specific use case
          required: true
